apiVersion: v1
kind: Service
metadata:
  name: voting-api-service
  labels:
    app: voting-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: voting-api
  sessionAffinity: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: voting-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: voting-api
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: voting-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: voting-api
subjects:
- kind: ServiceAccount
  name: voting-api
